### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by kom-senapati** [jaysaadana19/Collaborative-Code-Snippet-Repository#17]
Develop a captivating home page for the code-sharing platform with a responsive navbar, footer, and a compelling "Get Started" section for user onboarding.

**Tasks:**
1. Implement a responsive navigation bar.
2. Design and integrate a footer with essential links.
3. Create a "Get Started" section for user onboarding.

**Comment by kom-senapati** [comment]
I want to work on this issue.

**Comment by jaysaadana19** [comment]
Go ahead @kom-senapati
