### ISSUE TITLE
Re-initialize the project structure with React-Vite-Tailwind - (MERN)

### ISSUE THREAD

**Issue by IrfanshaikH-7** [jaysaadana19/Collaborative-Code-Snippet-Repository#18]
### Re-initialize the initial project set-up with

**Frontend**

- react+vite
- tailwind
- react-router-dom
- 
**Backend**

- express
- cors
- nodemon
- additionally set up the folder structure for controllers, routes and models

**Comment by kom-senapati** [comment]
I can work on this issue, after this I will make the home page.

**Comment by jaysaadana19** [comment]
Done @kom-senapati
