### ISSUE TITLE
Create Log In page 

### ISSUE THREAD

**Issue by sambitsingha** [jaysaadana19/Collaborative-Code-Snippet-Repository#26]
## Log In page creation 

The log in currently does not exist. I work like to work on it under SWOC'24

**Comment by jaysaadana19** [comment]
Ok go ahead @sambitsingha

**Comment by sambitsingha** [comment]
@jaysaadana19 **Check this figma file. This is first time working with Figma. Please suggest any changes neccessary**

https://www.figma.com/file/DS04enJNtCi4OS2qutMgKY/Login-Page?type=design&node-id=0%3A1&mode=design&t=4hUtXYoufPejnKmC-1

The page you seeing , I have already made the page and linked it. If this is alright , I will make the PR
