### ISSUE TITLE
Code Snippet Submission Form

### ISSUE THREAD

**Issue by jaysaadana19** [jaysaadana19/Collaborative-Code-Snippet-Repository#3]
Create a form to allow users to submit new code snippets.

Tasks:
Design and implement a user-friendly submission form.
Include fields for code, title, description, language, tags, etc.

**Comment by Yuvraj960** [comment]
Hey @jaysaadana19 , I did like to work on this issue

**Comment by jaysaadana19** [comment]
ok @Yuvraj960
