### ISSUE TITLE
Code Snippet Listing Page

### ISSUE THREAD

**Issue by jaysaadana19** [jaysaadana19/Collaborative-Code-Snippet-Repository#4]
Develop a page to display a list of code snippets with basic information.

Tasks:
Fetch and display code snippets from the database.
Implement pagination for better user experience.

**Comment by IrfanshaikH-7** [comment]
I'd like to work on this issue  : 
Surely I believe I can work on dummy data for now!

**Comment by jaysaadana19** [comment]
Go ahead @IrfanshaikH-7
