### ISSUE TITLE
Categories and Tags Implementation

### ISSUE THREAD

**Issue by jaysaadana19** [jaysaadana19/Collaborative-Code-Snippet-Repository#6]
Create a system for categorizing and tagging code snippets for better organization and searchability.

Tasks:
Set up database models for categories and tags.
Allow users to assign categories and tags when submitting a snippet.

**Comment by kom-senapati** [comment]
Once the database is decided, I would like to work on this issue.

**Comment by jaysaadana19** [comment]
Ok

**Comment by IrfanshaikH-7** [comment]
Should exclude the tag and category from submissions form! from my issue. #23

**Comment by jaysaadana19** [comment]
Yes if @kom-senapati has not started then you can add @IrfanshaikH-7

**Comment by kom-senapati** [comment]
Yes you can do @IrfanshaikH-7

**Comment by IrfanshaikH-7** [comment]
@kom-senapati you haven't started right - 🙄it feels like I'm stealing your issue

**Comment by kom-senapati** [comment]
> @kom-senapati you haven't started right - 🙄it feels like I'm stealing your issue

I dont have time now 🥹.

**Comment by IrfanshaikH-7** [comment]
I think this can be closed now! 😅as I have already done it
